name: Deploy Django App to Azure (FINAL)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Create and activate virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate

      - name: 4. Install dependencies
        run: |
          source antenv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn

      - name: 5. Cleaning testing files
        run: |
          rm -f db.sqlite3
          rm -f .env

      - name: 6. Run collectstatic
        run: |
          source antenv/bin/activate
          python manage.py collectstatic --noinput

      - name: 7. Make entrypoint.sh executable
        run: chmod +x entrypoint.sh

      - name: 8. Zip artifact for deployment
        run: |
          zip -r release.zip . -x ".git/*" -x ".github/*"

      - name: 9. Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read 

    steps:
      - name: 1. Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 2. Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projetoreco'
          package: release.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

          startup-command: "sh /home/site/wwwroot/entrypoint.sh"