name: Deploy Django App (MÃ©todo Oryx/Build no Servidor)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4



      - name: 2. Zip source code for deployment
        run: zip -r release.zip . -x ".git/*" -x ".github/*" -x "antenv/*"

      - name: 3. Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projetoreco'
          package: release.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

